services:

  redis-user:
    build: django/build/redis-user
    networks:
      - transcendence

  vue:
    build: vue/build/main
    image: transcendence_vue_login
    expose:
      - 8080
    networks:
       - transcendence
    volumes:
      - ./vue/volume/main:/Trascendence
      - vue_log:/Logs

  user:
    build:
      context: django/build/user
      args:
        - VAULT_TOKEN=$VAULT_TOKEN
        - VAULT_URL=$VAULT_URL
        - ADMIN=$ADMIN

    container_name: transcendence_dj_user
    depends_on:
      - pg-login

    image: transcendence_dj_user
    networks:
      - transcendence
    volumes:
      - ./django/volume/user:/app
      - ./django/log:/log
      - dependencies_avatar_data:/avatar

  login:
    build:
      context: django/build/login
      args:
        - VAULT_TOKEN=$VAULT_TOKEN
        - VAULT_URL=$VAULT_URL
        - ADMIN=$ADMIN

    container_name: transcendence_dj_login
    depends_on:
      - pg-login
    image: transcendence_dj_login
    networks:
      - transcendence
    volumes:
      - ./django/volume/login:/app
      - ./django/log:/log

  gateway:
  
    build:
      context: django/build/gateway
      args:
        - VAULT_TOKEN=$VAULT_TOKEN
        - VAULT_URL=$VAULT_URL
        - ADMIN=$ADMIN
    container_name: transcendence_dj_gateway
    depends_on:
      - pg-login
      - login
    image: transcendence_dj_gateway
    networks:
      - transcendence
    ports:
      - 4242:4242
    volumes:
      - ./django/volume/gateway:/app
      - ./django/log:/log

  pg-login:
    build: django/build/pg-login
    container_name: transcendence_pg_login
    image: transcendence_pgbase_login
    networks:
      - transcendence
    restart: always
    volumes:
      - pg-login_data:/var/lib/postgresql/data

volumes:

  vue_log:
    driver: local
    driver_opts:
            type: none
            o: bind
            device: vue/log

  pg-login_data:
  dependencies_avatar_data:
    external: true

networks:
  transcendence: 
