services:

  nginx-waf:
    build: nginx-waf/build/main
    container_name: transcendence_nginx_waf
    image: transcendence_nginx_waf
    environment:
      - PARANOIA=1
      - BLOCKING_PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - REPORTING_LEVEL=2
    expose:
      - 80
    networks:
      - proxy
      - develop_transcendence
      - devops_monitor
    volumes:
      - ./nginx-waf/build/main/conf/before-crs.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./nginx-waf/build/main/conf/after-crs.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
      - ./nginx-waf/build/main/conf/default.conf:/etc/nginx/templates/conf.d/default.conf.template

  haproxy:

    build: ./haproxy/build/main
    container_name: transcendence_haproxy
    image: transcendence_haproxy

    networks:
      - proxy
      - devops_monitor
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/certs

  vault:
    build: ./vault/build/main
    cap_add:
      - IPC_LOCK
    container_name: transcendence_vault
    depends_on:
      - postgre-vault
    env_file:
      - .envs/.env.vault
    image: transcendence_vault
    networks:
      - develop_transcendence
    ports:
      - 8200:8200
    restart: always

  postgre-vault:  
    build: ./vault/build/postgre
    container_name: transcendence_postgre_vault
    image: transcendence_postgre_vault
    env_file:
      - .envs/.env.vault

    networks:
      - develop_transcendence
    restart: always  
    volumes:
      - pg_vault:/var/lib/postgresql/data

volumes:

  pg_vault:
  certs:
  webroot:

networks:
  proxy:
  develop_transcendence:
    external: true

  devops_monitor:
    external: true